# 应用名称
server:
  port: 8762

spring:
  application:
    name: provider
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
    service:
      name: provider
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


